version: "3.7"
services:
  minio:
    image: minio/minio
    container_name: mlflow_minio
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
        - /mnt/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: minio server --console-address ":9001" /data
